### PR TITLE
20 configure ci to run tests

### PR DESCRIPTION
**Pull request by ajjimenezm**
Hello Marco, do not mind for the big number of commits as they were necessary to get the pipeline running, they only included minor changes mainly for debugging. I want to point out a few challenges and peculiarities that I have encountenred when setting up the pipeline, and some places where it could be improven if necessary.

As you can see, the pipeline has to run _cabal v2-install_ each time it runs, and this causes that the running time is approximately 5 minutes. But I have not found a way to skip this, as the tests from the parser would not work properly. If you have any idea I would gladly work on it.

Also, the parser tests and the acceptance tests are run in the same step, this is to avoid having to run _cabal v2-install_ 2 times, because CircleCI apparently does not store builds within different steps. However I have added some debug messages so that if the pipeline fails we can see the reason, so I think that it is not a big problem.

### CODE REVIEW

**Review by mfeliu — CHANGES_REQUESTED** [review]
First, document somewhere what Dockerfile you have used; maybe, a Dockerfile at the root of the repository may work.
Second, try running `cabal install --only-dependencies` in both repositories **while** building the image; this will pre-fetch and build the dependencies, which I think is the most expensive task in the CI.
As a final step, rewrite the commit history (you can squash them all if it makes sense for you) to have a few commits.

**Comment by ajjimenezm** [comment]
@mfeliu The Dockerfile I have used is in the root directory. If you mean what image I have used as base for that Dockerfile, that is the image that we originally created for the other repository _plexil-rwl-support/semantic-tests_.

I tried to pre-install the dependencies but it is not possible, as the pipeline adds the repository (and all its files) when it is triggered, with the _checkout_ command. So I am not sure if there is any workaround.

Regarding the numerous commits it is not necessary to rewrite the commit history manually, when you approve the Pull Request and consequently merge it, you can chose the option Squash & merge from the dropdown menu in the "Merge pull request button".

**Comment by mfeliu** [comment]
@ajjimenezm please refactor the Dockerfile so that it is a "standalone" Dockerfile that only uses standard (for example ubuntu) images as base images.
What you have to do to preinstall dependencies is to add a version of the repository to the building context of the Dockerfile (check the documentation for the ADD Dockerfile command). Then, you can access the files in the Dockerfile script and you can run cabal.
I prefer that you rewrite the git history, because it is your responsibility to document what you have done in the commit message. Make yourself comfortable rewriting history, it is very useful.

**Comment by ajjimenezm** [comment]
@mfeliu Okay, I will take a look

**Comment by ajjimenezm** [comment]
@mfeliu I have introduced the changes you have requested, including the update image. In this way the pipeline only takes 1 minute to execute approximately. I have also squashed the commits. I hope everything looks good now.

**Comment by mfeliu** [comment]
@ajjimenezm, please fix the commit message to follow the unwritten convention in other commits of the repository.

**Comment by ajjimenezm** [comment]
@mfeliu Yes sorry, I forgot. How do you think that I should name what I have done? Maybe something like _Pipeline:_ in case we introduce changes in the future?

**Comment by mfeliu** [comment]
> @mfeliu Yes sorry, I forgot. How do you think that I should name what I have done? Maybe something like _Pipeline:_ in case we introduce changes in the future?

I think something like "ci: ..." works.

**Comment by ajjimenezm** [comment]
@mfeliu All set

**Review by mfeliu — APPROVED** [review]

**Comment by mfeliu** [comment]
I am going to merge the current state. Please @ajjimenezm look at the changes I have introduced. I am going to open a new issue so that you integrate the "regression tests" into the CI.

**Pull request merged**
