### PR TITLE
semantics: Fix updateInterfaceHistory

### PR DESCRIPTION
**Pull request by mfeliu**
Currently, `updateInterfaceHistory` is building a unique set of external inputs instead of a list of sets.

Make `updateInterfaceHistory` prepend the current set of external inputs to the list contained in the `interface-history` cell.

Resolves: #47

### CODE REVIEW

**Comment by mfeliu** [comment]
@mikedalal , I think I already fix the issue but I forgot to push it. Can you check that is works with your example? Thank you.

**Comment by mikedalal** [comment]
@mfeliu The original problem is fixed, but now the counterexample looks wrong in a different way.  I will attach the files after showing you the before and after.  Here's a property failure counterexample before the fix:
```
reduce in M-CHECK : customModelCheck(init, liveness3, transitionCounterexample) .
rewrites: 10176 in 14ms cpu (14ms real) (721497 rewrites/second)
result TransitionCounterexample: 
Input(noExternalInputs)
--> 
Input(stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(stateLookup('time, nilarg, val(520)) stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSuccess) stateLookup('time, nilarg, val(520)) stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(stateLookup('time, nilarg, val(1322)) stateLookup('PointedAtTarget, nilarg, val(false)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSuccess) stateLookup('time, nilarg, val(520)) stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(commandAck('camera_capture_image, val(50) val(1), CommandSuccess) stateLookup('time, nilarg, val(1322)) stateLookup('PointedAtTarget, nilarg, val(false)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSuccess) stateLookup('time, nilarg, val(520)) stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(stateLookup('time, nilarg, val(1350)) commandAck('camera_capture_image, val(50) val(1), CommandSuccess) stateLookup('time, nilarg, val(1322)) stateLookup('PointedAtTarget, nilarg, val(false)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSuccess) stateLookup('time, nilarg, val(520)) stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(stateLookup('time, nilarg, val(1373)) stateLookup('time, nilarg, val(1350)) commandAck('camera_capture_image, val(50) val(1), CommandSuccess) stateLookup('time, nilarg, val(1322)) stateLookup('PointedAtTarget, nilarg, val(false)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSuccess) stateLookup('time, nilarg, val(520)) stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(commandAck('camera_power_off, nilarg, CommandSuccess) stateLookup('time, nilarg, val(1373)) stateLookup('time, nilarg, val(1350)) commandAck('camera_capture_image, val(50) val(1), CommandSuccess) stateLookup('time, nilarg, val(1322)) stateLookup('PointedAtTarget, nilarg, val(false)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSuccess) stateLookup('time, nilarg, val(520)) stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(stateLookup('CameraOn, nilarg, val(false)) commandAck('camera_power_off, nilarg, CommandSuccess) stateLookup('time, nilarg, val(1373)) stateLookup('time, nilarg, val(1350)) commandAck('camera_capture_image, val(50) val(1), CommandSuccess) stateLookup('time, nilarg, val(1322)) stateLookup('PointedAtTarget, nilarg, val(false)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSuccess) stateLookup('time, nilarg, val(520)) stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Loop{
 Input(stateLookup('time, nilarg, val(1394)) stateLookup('CameraOn, nilarg, val(false)) commandAck('camera_power_off, nilarg, CommandSuccess) stateLookup('time, nilarg, val(1373)) stateLookup('time, nilarg, val(1350)) commandAck('camera_capture_image, val(50) val(1), CommandSuccess) stateLookup('time, nilarg, val(1322)) stateLookup('PointedAtTarget, nilarg, val(false)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSuccess) stateLookup('time, nilarg, val(520)) stateLookup('CameraOn, nilarg, val(true)) commandAck('camera_power_on, nilarg, CommandSuccess) stateLookup('time, nilarg, val(510)) commandAck('camera_power_on, nilarg, CommandSentToSystem) stateLookup('time, nilarg, val(500)) commandAck('slew, val(1200) val(-9.0e+1) val(0.0), CommandSentToSystem) stateLookup('time, nilarg, val(122)) stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
}
```

**Comment by mikedalal** [comment]
Here's the same failure after the fix.  We've lost everything except the first word.  And then so many `noExternalInputs`.  I don't know how to interpret this.

```
reduce in M-CHECK : customModelCheck(init, liveness3, transitionCounterexample) .
rewrites: 10176 in 17ms cpu (18ms real) (568237 rewrites/second)
result TransitionCounterexample: 
Input(noExternalInputs)
--> 
Input(stateLookup('time, nilarg, val(0)) stateLookup('PointedAtTarget, nilarg, val(false)) stateLookup('CameraOn, nilarg, val(false)))
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Loop{
 Input(noExternalInputs)
}
```

**Comment by mikedalal** [comment]
Here are the plan, script, and properties that produced the output above.
[counterexample.tar.gz](https://github.com/plexil-rwl-support/PLEXIL5/files/11740633/counterexample.tar.gz)

**Comment by mfeliu** [comment]
It was a problem with pretty-printer used in customModelChecker. If there were more than one set of external inputs in the interface-history cell, it would produce noExternalInputs as default. Please double check @mikedalal .

**Review by mikedalal — APPROVED** [review]
Looks good!

I have tried with scripts only from `sequenceGenerator` but this is really all I've been using lately.

**Pull request merged**
