### PR TITLE
semantics: Implement hasCmdHandle? and hasNoCmdHandle? properties

### PR DESCRIPTION
**Pull request by mfeliu**
Resolves: #21

### CODE REVIEW

**Comment by mfeliu** [comment]
@mikedalal , please confirm if these properties provide the required expressiveness.

**Comment by mikedalal** [comment]
I'm struggling with the syntax:
```
Warning: "Plan3-properties.maude", line 22 (mod M-CHECK): no parse for statement
eq [liveness3] : liveness3 = <> hasCmdHandle? ('camera_capture_image, 'executing) .
```
I've tried both arguments with and without quotes...

**Comment by mfeliu** [comment]
Hi Mike,

I see that Maude does not help many times with parsing/typing problems. To debug these types of issues, I recommend to reduce slices of the code. For example, try to reduce the expression you are trying to assign to a constant:
```Maude
$ maude
Maude> load src/plexilite.maude
Maude> red <> hasCmdHandle? ('camera_capture_image, 'executing) .
  Warning: <standard input>, line 1: didn't expect token 'executing:
  <> hasCmdHandle? ( 'camera_capture_image , 'executing <---*HERE*
  Warning: <standard input>, line 1: no parse for term.
```
Now we know the `'executing` QID is offending, so we check the type of the `hasCmdHandle?` operator.
```Maude
  op hasCmdHandle? : NeQualified CommandHandle -> Prop [ctor] .
```
Then it needs a `CommandHandle` that you can search in the code:
```Maude
fmod COMMAND-HANDLE  is
  sort CommandHandle .
  op CommandSentToSystem   : -> CommandHandle .
  op CommandAccepted       : -> CommandHandle .
  op CommandRcvdBySystem   : -> CommandHandle .
  op CommandFailed         : -> CommandHandle .
  op CommandDenied         : -> CommandHandle .
  op CommandSuccess        : -> CommandHandle .
  op CommandInterfaceError : -> CommandHandle .
  op CommandHandleMax      : -> CommandHandle .
endfm
```
So any of those operators are the ones that you can put as the second argument of the property. For example:
```Maude
Maude> red <> hasCmdHandle? ('camera_capture_image, CommandAccepted) .
  reduce in PLEXILITE-PREDS : <> hasCmdHandle?('camera_capture_image, CommandAccepted) .
  rewrites: 1 in 0ms cpu (0ms real) (1000000 rewrites/second)
  result Formula: True U hasCmdHandle?('camera_capture_image, CommandAccepted)
```
The command `hasCmdHandle?` and `hasNoCmdHandle?` only check for the handles. If you are interested in the *state* of execution of the node use the `hasStatus` property.

**Comment by mikedalal** [comment]
Thanks Marco, I see that I was making a silly mistake -- confusing node state with command handle.  But your debugging tips are very helpful!

Unfortunately, I've not had success with the new properties.  I've attached a simple plan, script, and two command handle properties that I think should hold, but neither does.   My result is:
```
==========================================
reduce in M-CHECK : customModelCheck(init, liveness1, transitionCounterexample) .
rewrites: 1014 in 1ms cpu (1ms real) (689795 rewrites/second)
result Bool: true
==========================================
reduce in M-CHECK : customModelCheck(init, liveness2, transitionCounterexample) .
rewrites: 2210 in 2ms cpu (2ms real) (1080684 rewrites/second)
result TransitionCounterexample: 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Loop{
 Input(commandAck('foo, nilarg, CommandSuccess))
}
==========================================
reduce in M-CHECK : customModelCheck(init, liveness3, transitionCounterexample) .
rewrites: 2208 in 2ms cpu (2ms real) (960000 rewrites/second)
result TransitionCounterexample: 
Input(noExternalInputs)
--> 
Input(noExternalInputs)
--> 
Loop{
 Input(commandAck('foo, nilarg, CommandSuccess))
}
```

[CommandHandleTests.tar.gz](https://github.com/plexil-rwl-support/PLEXIL5/files/11425275/CommandHandleTests.tar.gz)

**Comment by mfeliu** [comment]
> Thanks Marco, I see that I was making a silly mistake -- confusing node state with command handle. But your debugging tips are very helpful!
> 
> Unfortunately, I've not had success with the new properties. I've attached a simple plan, script, and two command handle properties that I think should hold, but neither does. My result is:
> 
> ```
> ==========================================
> reduce in M-CHECK : customModelCheck(init, liveness1, transitionCounterexample) .
> rewrites: 1014 in 1ms cpu (1ms real) (689795 rewrites/second)
> result Bool: true
> ==========================================
> reduce in M-CHECK : customModelCheck(init, liveness2, transitionCounterexample) .
> rewrites: 2210 in 2ms cpu (2ms real) (1080684 rewrites/second)
> result TransitionCounterexample: 
> Input(noExternalInputs)
> --> 
> Input(noExternalInputs)
> --> 
> Loop{
>  Input(commandAck('foo, nilarg, CommandSuccess))
> }
> ==========================================
> reduce in M-CHECK : customModelCheck(init, liveness3, transitionCounterexample) .
> rewrites: 2208 in 2ms cpu (2ms real) (960000 rewrites/second)
> result TransitionCounterexample: 
> Input(noExternalInputs)
> --> 
> Input(noExternalInputs)
> --> 
> Loop{
>  Input(commandAck('foo, nilarg, CommandSuccess))
> }
> ```
> 
> [CommandHandleTests.tar.gz](https://github.com/plexil-rwl-support/PLEXIL5/files/11425275/CommandHandleTests.tar.gz)

The problem is that the command identifiers in the specification of the properties have to be fully qualified as in:
```Maude
  *** Command foo eventually succeeds
  op liveness2 : -> Prop .
  eq [liveness2] :
    liveness2 = <> hasCmdHandle?('foo . 'Node1 . 'CommandHandleTests, CommandSuccess) .

  *** Command bar is never called
  op liveness3 : -> Prop .
  eq [liveness3] :
    liveness3 = [] hasNoCmdHandle?('bar . 'Node1 . 'CommandHandleTests) .
```
In this case `liveness2` is satisfied but `liveness3` is not, for the provided example.

**Comment by mikedalal** [comment]
Thanks for the clarification, Marco.

I'm now puzzled by why `liveness3` is failing (I corrected it to look at `Node2).  The `bar` command can never be called, so should never have a command handle.  I tried testing it for having all the available handles, and the property still failed.   Could this be a bug?

**Comment by mfeliu** [comment]
> Thanks for the clarification, Marco.
> 
> I'm now puzzled by why `liveness3` is failing (I corrected it to look at `Node2`). The `bar` command can never be called, so should never have a command handle. I tried testing it for having all the available handles, and the property still failed. Could this be a bug?

Sorry, this was my mistake with the answer. The full qualified id of the `bar` command was wrong. Try this instead:
```Maude
  op liveness3 : -> Prop .
  eq [liveness3] :
    liveness3 = [] hasNoCmdHandle?('bar . 'Node2 . 'CommandHandleTests) .
```

**Comment by mikedalal** [comment]
> Sorry, this was my mistake with the answer. The full qualified id of the `bar` command was wrong. Try this instead:
> 
> ```
>   op liveness3 : -> Prop .
>   eq [liveness3] :
>     liveness3 = [] hasNoCmdHandle?('bar . 'Node2 . 'CommandHandleTests) .
> ```
> 
> It returns `true` as expected.

I had made this correction myself.  I just tried again in a fresh environment, using exactly the property above, and it still fails.  I'm invoking the checker with:
```
red customModelCheck(init,liveness3,transitionCounterexample) .
```
Do you have any idea why our result would be different?

**Comment by mikedalal** [comment]
I just retested the latest version of this branch using the example above, and the `liveness3` property still fails.  I even removed call to `bar` from the plan.

**Comment by mfeliu** [comment]
I have found the problem. The thing there is an ambiguity with `hasNoCmdHandle?`, it was returning true only when the command had been executed (not completed yet) but no command handle had been received. In the current temporary fix I have upload, it returns true also when the command was never executed.

**Comment by mikedalal** [comment]
Glad you found the issue, @mfeliu .  The problem is fixed in my example.

**Pull request merged**
