### PR TITLE
semantics: Add isLookup? and isLookupKnown? properties

### PR DESCRIPTION
**Pull request by mfeliu**
The behavior is explained in the commit messages.

### CODE REVIEW

**Comment by mikedalal** [comment]
@mfeliu, the `isLookupKnown?` predicate looks perfect,  in name and semantics.  

However,`isLookup?` is limited in usefulness because it only tests equivalence when we often want ordinal comparisons.  A more useful operator would be an accessor, e.g.
```
op lookupValue : NeQualified Arguments -> Value .
```
which can then be compared with any other value, including that of another Lookup.  Would this be possible?

**Comment by mfeliu** [comment]
It is possible. But let's give some more concrete examples to bound this feature. For example, how would you build an boolean expression that represents that possible comparison you are interested in? Maybe something like these:
```Maude
lookupValue(...) == lookupValue(...)
lookupValue(...) <= 4
```

**Comment by mikedalal** [comment]
The following would be desirable:
```
e1 == e2
e1 != e2  (not equal)
e1 <  e2
e1 <= e2
e1 >  e2
e1 >= e2
```
where `e1` and `e2` are `lookupValue(...)` or any value type returnable by `lookupValue`.  Maude-appropriate syntax can be used as needed.

Would allowing `e1` and `e2` to be arithmetic expressions (at least plus, minus, times) of numeric expressions be easy, or is that out of scope here?

**Comment by mfeliu** [comment]
There is already a way to include arithmetic expressions as properties with the following constructors:
```Maude
  op isTrue? : Expression -> Prop .
  op isFalse? : Expression -> Prop .
```
What do you think about this syntax?

**Comment by mfeliu** [comment]
@mikedalal should we maybe cancel this commit and try to express this properties as expressions?

**Comment by mikedalal** [comment]
> @mikedalal should we maybe cancel this commit and try to express this properties as expressions?

@mfeliu, yes that sounds good and it's a more general solution.

**Pull request closed without merging**
